[server]
host = "0.0.0.0"
port = 50051

[redis]
redis_host="redis"
redis_port=6379
uri = "tcp://127.0.0.1:6379"

[[rules]]
endpoint = "/api/v1/login"
strategy = "fixed_window"
limit = 5
window_seconds = 60

[[rules]]
endpoint = "/api/v1/search"
strategy = "token_bucket"
limit = 10
window_seconds = 1  # For token bucket, this acts as refill rate
